spring:
  cloud:
    config:
      label: master
      server:
        #native:
         # search-locations: file:E:\2016\workspace\micro-finger-config
        git:
#          uri: https://github.com/9ban/micro-finger-config.git
          uri: file:E:\2016\workspace\micro-finger-config
  #profiles:
  #  active: native


server:
  port: 8087
